### PR TITLE
Add Dutch Ordinalizer

### PR DESCRIPTION
**Pull request by dampee**

### CODE REVIEW

**Comment by MehdiK** [comment]
Thanks for the contribution. Can you please add unit tests?

**Comment by dampee** [comment]
Sure. Just pushed the commits. Tests have passed on teamcity.

**Comment by MehdiK** [comment]
Thanks for the contribution. This is now released to NuGet as v1.37.0.

**Comment by dampee** [comment]
cool!  Thanks a lot for keeping me posted

**Pull request merged**
