### PR TITLE
English

### PR DESCRIPTION
**Pull request by Roddhes88**
Pull request for estimated frequency as string

### CODE REVIEW

**Comment by MehdiK** [comment]
This PR is confusing! These are the commits I made over a year ago in an attempt to implement English tenses but I had to abandon it because it felt rather impossible to do that without having a complete dictionary.

Your PR description says something else though! Did you mean to send a PR for something else?

**Comment by MehdiK** [comment]
I have to close this PR. As much as I would love to have that implementation in, it's just incomplete!

**Comment by Roddhes88** [comment]
Hello Mehdi, well I'm new on GitHub, it's my first pull request ever and
I'm afraid I didn't do exactly what I meant to :/
I've locally commited the files I added/modified, (Frequency.cs,
DateHumanizeExtension.cs, FrequencyEnum.cs, FrequencyHumanizeExtensions.cs,
NotStandardTimeExtensions.cs, etc.) but as I didn't really know what to do
then, I decided to create a pull request where I could, should have I done
it otherwise?


Thx in advance.


Best regards,
Rodolphe

2015-03-24 10:45 GMT+01:00 Mehdi Khalili <notifications@github.com>:

**Comment by MehdiK** [comment]
Hi @Roddhes88,

Thanks for the comment.

This might help:

```
git remote remove origin
git remote remove upstream // you may not need this. If you have defined other remotes go through them and remote them all
git remote add upstream https://github.com/MehdiK/Humanizer.git
git remote add origin the-link-to-your-fork-as-found-on-your-repo-home-page-on-github
git checkout master  // to make sure you're on master
git pull upstream master --rebase // just making sure you have the latest code while not losing your changes
git checkout -b frequency // create a 'frequency' branch off master 
git push origin frequency // this will push to your fork on github - assuming you have origin define properly
```

At this point you should have a clean branch on github. Go to your GitHub repo and submit a PR from the branch you just pushed.

I hope this helps.

**Comment by Roddhes88** [comment]
Hi MehdiK,

Thanks a lot for the help !
I think now I've succeeded in pushing what I've coded. Please let me know
what you think about it.


Best regards,
Rodolphe

2015-03-25 2:21 GMT+01:00 Mehdi Khalili <notifications@github.com>:

**Pull request closed without merging**
