### PR TITLE
Add rule for is/are

### PR DESCRIPTION
**Pull request by MatthewSteeples**
I don't know whether this belongs in the same area or not, but we'd like the functionality to extend to the following kinds of sentences:

There is 1 case
There are 5 cases

We can obviously already to "case".ToQuantity(5) to get cases, but we'd like to be able to do the auxiliary verb (is/are) as well.

I've added those entries in but would be happy to get feedback on whether this is the right place or not.

### CODE REVIEW

**Comment by MehdiK** [comment]
Thanks @MatthewSteeples. This is alright.

P.S. I was thinking we're not too far from `"There is {quantity} case".ToQuantity(5) => "There are 5 cases"`

**Comment by MehdiK** [comment]
Please add your PR to the releasenotes file and leave me a comment when done and I'll merge. Thanks.

**Comment by MehdiK** [comment]
I added the release notes, rebased and pushed. Thanks.

**Comment by MehdiK** [comment]
This is now released to NuGet as v1.35.0. Thanks for the contribution.

**Comment by MatthewSteeples** [comment]
@MehdiK Thanks for merging this. I'll know what to do when we've got other suggestions now. C# 6 does some interesting things with string interpolation that might make your example above a lot more attainable. I've not looked into it much yet.

**Pull request closed without merging**
