### PR TITLE
Added a build target for .NET 4.0 Client Profile.

### PR DESCRIPTION
**Pull request by Phyxion**
This is for #308 and is by far the easiest solution without having to copy everything constantly around. If this is accepted, it would be nice to update NuGet as well. I also changed the build.bat to include the 4.0 CP.

### CODE REVIEW

**Comment by MehdiK** [comment]
Thanks @Phyxion. I've merged this. The NuGet update would require publishing two separate packages: one for CPL and one for 4.0 CP I believe, right?

**Comment by Phyxion** [comment]
No, you can use one NuGet package with multiple targets.

https://docs.nuget.org/create/creating-and-publishing-a-package#import-msbuild-targets-and-props-files-into-project

**Comment by MehdiK** [comment]
Thanks for the contribution. This is now released to NuGet as v1.37.0. A PR on multiple targets would be nice :)

**Comment by Phyxion** [comment]
I wish I could help but I'm not an expert with NuGet. I do know that several NuGet packages have multiple targets so it should be possible. The NuGet 1.37.0 is still only the PCL so not useful yet for .NET 4.0 clients.

That said, I think it might be possible to just add the 4.0 dll to the "lib\net40" folder as I'm not seeing anything differently in the other files with NuGet packages that have multiple targets. I think this will suffice:
https://github.com/MehdiK/Humanizer/compare/master...Phyxion:patch-1

**Comment by MehdiK** [comment]
It takes a bit more work than that. The build script should move the result of different profiles into different folders which get copied into the NuGet folder structure and then packaged up. This is a needed change and we will tackle it.

**Comment by Phyxion** [comment]
I expected as much, it looked a bit too easy. Looking forward to your commit for this!

**Pull request merged**
