### PR TITLE
Added pt-BR localization for CollectionFormatter

### PR DESCRIPTION
**Pull request by akamud**

### CODE REVIEW

**Comment by hazzik** [comment]
I prefer to wait until #386 is merged

**Comment by akamud** [comment]
Didn't notice that. I'll keep an eye to change the localization when it's merged.

**Comment by hazzik** [comment]
Thanks, this has been superseded by #386

**Comment by MehdiK** [comment]
Thanks for the PR @akamud and thanks for holding this up @hazzik. Yeah, #386 is pretty slick :)

**Pull request closed without merging**
