### PR TITLE
use lazy initialization for Vocabularies

### PR DESCRIPTION
**Pull request by jeremysimmons**
resolve bug #437 using Lazy<T>

### CODE REVIEW

**Comment by MehdiK** [comment]
Thanks for the fix. 

P.S. If you write your comments as 'Fixes #issue_no' or 'Resolves #issue_no' GitHub will close the issue when the PR is merged automatically.

**Comment by jeremysimmons** [comment]
does github close issues from comments if you do not have contribute permission to the repo?

**Comment by jeremysimmons** [comment]
shame on me for not checking...
https://help.github.com/articles/closing-issues-via-commit-messages/

looks like it closes on merge to master...

**Comment by MehdiK** [comment]
Yes. No worries. Looking forward to seeing more great contributions from you :)

**Comment by MehdiK** [comment]
This is now released to NuGet as v1.37.7. Thanks for the fix.

**Pull request merged**
